# Smart Home Command Validation Configuration

# Supported devices
devices:
  - lights
  - thermostat
  - tv
  - music
  - fan
  - blinds
  - door
  - speakers
  - vacuum
  - air_conditioner
  - heater

# Supported locations
locations:
  - kitchen
  - living room
  - bedroom
  - bathroom
  - hallway


# Supported actions
actions:
  - on
  - off
  - set
  - adjust
  - open
  - close
  - play
  - pause
  - stop
  - start
  - increase
  - decrease
  - lock
  - unlock

# Location synonyms and expansions
synonyms:
  locations:
    all rooms:
      - kitchen
      - living room
      - bedroom
      - bathroom
      - office
      - hallway
      - dining room
    house:
      - kitchen
      - living room
      - bedroom
      - bathroom
      - office
      - hallway
      - dining room
    downstairs:
      - kitchen
      - living room
      - hallway
      - dining room
    upstairs:
      - bedroom
      - bathroom
      - office
  
  devices:
    lights:
      - light
      - lamp
      - lighting
    music_player:
      - speaker
      - music
      - radio
