# Model-specific configurations
microsoft/phi-2:
  temperature: 0.7  # Lower temperature for more stable outputs
  do_sample: false  # Disable sampling for deterministic outputs
  return_token_type_ids: false

nilq/mistral-1L-tiny:
  return_token_type_ids: false

EleutherAI/pythia-70m:
  return_token_type_ids: false
  temperature: 1.0  # Use default temperature
  do_sample: false  # Disable sampling to avoid probability issues
  num_beams: 1      # Use greedy decoding

# Add more model configurations below 